### ISSUE TITLE
Support api level < 21?

### ISSUE THREAD

**Issue by jaychang0917** [googlecreativelab/shadercam#10]
Hi, will this library support api level less than 21?

**Comment by trippedout** [comment]
nope - this library is based off the camera2 apis, introduced first in api 21 and the standard for camera work in android since then.

altho it should be trivial to implement the renderer for the old camera apis, as they both used surfaces for rendering their content.

**Comment by jaychang0917** [comment]
But `MediaRecorder` seems only support recording surface on api 21+, do you have any alternative solution?

**Comment by trippedout** [comment]
a quick google shows a few options, im sure there are plenty more

https://github.com/orangesignal/orangesignal-android-camera
https://github.com/yulu/ShaderCam
http://nhenze.net/?p=172

**Comment by jaychang0917** [comment]
Your links seems not related to recording a surface.

**Comment by trippedout** [comment]
ah - i think the only way to do this pre api 21 is with native code. media recorder only took a source variable, camera or otherwise, before allowing an arbitrary surface. 

you're hitting 60+% of devices with api 21 nowadays tho, but sorry i dont have any more info for you

**Comment by jaychang0917** [comment]
thanks your information!
