### ISSUE TITLE
ShaderCam + TextOverlayEffect

### ISSUE THREAD

**Issue by zhogar** [googlecreativelab/shadercam#12]
Hi,
Is it possible to output text using your library, to preview the camera?

Thanks you.

**Comment by timurgilfanov** [comment]
Look at [Texample2](https://github.com/Scriptgate/Texample2). It's render text in OpenGL ES 2 on Android. You need to extend CameraRenderer in ShaderCam and add text rendering from Texample2Renderer. I'm working on it now and have first buggy version.

**Comment by zhogar** [comment]
I managed to superimpose text in [Grafika](https://github.com/google/grafika), but on Camera2 I wanted to use [RenderScript](https://developer.android.com/guide/topics/renderscript/compute.html) (it did not work).

**Comment by jitenderjovi** [comment]
Hi Timur,

are your able to render the text on camera .. I have been trying from last 1 week but not success. If you have any code please help

**Comment by timurgilfanov** [comment]
@jitenderjovi look at [my fork](https://github.com/timurgilfanov/shadercam/commits/master)

**Comment by jitenderjovi** [comment]
@timurgilfanov  Great man. Thanks a lot. it works :)

**Comment by zhogar** [comment]
@jitenderjovi Did you succeed? Can I see the code?

**Comment by jitenderjovi** [comment]
@zhogar 
Downloaded code from this link https://github.com/googlecreativelab/shadercam working perfectly for me

**Comment by zhogar** [comment]
There is a fragment shader:
```
#extension GL_OES_EGL_image_external : require

precision mediump float;

varying vec2 vTextureCoord;

uniform samplerExternalOES sTexture;
uniform sampler2D oTexture;

void main()
{
    vec4 bg_color = texture2D(sTexture, vTextureCoord);
    vec4 fg_color = texture2D(oTexture, vTextureCoord);

    float colorR = (1.0 - fg_color.a) * bg_color.r + fg_color.a * fg_color.r;
    float colorG = (1.0 - fg_color.a) * bg_color.g + fg_color.a * fg_color.g;
    float colorB = (1.0 - fg_color.a) * bg_color.b + fg_color.a * fg_color.b;

    gl_FragColor = vec4(colorR, colorG, colorB, bg_color.a);
}
```
1) How to use it with [ExampleRenderer.java](https://github.com/googlecreativelab/shadercam/blob/master/shadercam-example/src/main/java/com/androidexperiments/shadercam/example/gl/ExampleRenderer.java)?
2) And what should be the vertex shader?

Thank you.

**Comment by jeetdholakia** [comment]
@timurgilfanov I used your forked project on Android devices running 7.1.1 and 8.0 and both of them just show the first frame for the entire length of the video... this is also a problem in the original project...

**Comment by zhogar** [comment]
I use GLES and shader:
`#extension GL_OES_EGL_image_external : require
precision mediump float;
varying vec2 vTextureCoord;
uniform samplerExternalOES sTexture;
uniform sampler2D oTexture;
void main() {
	vec4 bg_color = texture2D(sTexture, vTextureCoord);
	vec4 fg_color = texture2D(oTexture, vTextureCoord);
	float colorR = (1.0 - fg_color.a) * bg_color.r + fg_color.a * fg_color.r;
	float colorG = (1.0 - fg_color.a) * bg_color.g + fg_color.a * fg_color.g;
	float colorB = (1.0 - fg_color.a) * bg_color.b + fg_color.a * fg_color.b;
	gl_FragColor = vec4(colorR, colorG, colorB, bg_color.a);
}`
